data<-read.table("household_power_consumption.txt",nrow=2880,skip=66637,sep=";")
png(filename="plot3.png",width=480,height=480)
combine<-c(as.POSIXct(paste(data$V1, data$V2), format = "%d/%m/%Y %T"))
par(mfrow=c(2,2))
par(mar=c(4,4,4,4))
plot(combine, data$V3,xlab="",ylab="Global Active Power",type="l")
plot(combine, data$V5,xlab="datetime",ylab="Voltage",type="l")
plot(combine,data$V7,xlab="",ylab="Energy sub metering",type="l")
lines(combine,data$V8,col="red")
lines(combine,data$V9,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.4,lty=1:1,col=c("black","red","blue"),bty='n')
plot(combine,data$V4,xlab="datetime",ylab="Global_reactive_power",type="l")

